#define NUM_OF_MOD_INV_TESTS 4
#define NUM_OF_MOD_PRODUCT_TESTS 3
#define NUM_OF_MOD_POWER_TESTS 4
#define NUM_OF_COPRIME_TESTS 5
#define NUM_OF_TOTIENT_TESTS 6
#define NUM_OF_MOD_EVAL_TESTS 1

long MOD_PRODUCT_NUM_PAIRS[NUM_OF_MOD_PRODUCT_TESTS][2] = {{5,6}, {41,3}, {16, 3}};
long MOD_PRODUCT_MODS[NUM_OF_MOD_PRODUCT_TESTS] = {10, 8, 19};
long MOD_PRODUCT_PRODUCTS[NUM_OF_MOD_PRODUCT_TESTS] = {0, 3, 10};

long MOD_INV_NUMS[NUM_OF_MOD_INV_TESTS] = {5, 4, 53, 3};
long MOD_INV_MODS[NUM_OF_MOD_INV_TESTS] = {12, 23, 105, 7};
long MOD_INV_INVS[NUM_OF_MOD_INV_TESTS] = {5, 6, 2, 5};

int POLY_DEGREE[NUM_OF_MOD_EVAL_TESTS] = {2};
long POLY_COEFFS[NUM_OF_MOD_EVAL_TESTS][3] = {{1,-2,1}};
long POLY_MOD[NUM_OF_MOD_EVAL_TESTS] = {2147483646};
long POLY_X[NUM_OF_MOD_EVAL_TESTS] = {715827883};
long POLY_EVAL[NUM_OF_MOD_EVAL_TESTS] = {0};
